name: Run CIS Benchmark with Ansible

on:
  workflow_dispatch:  # You can trigger manually

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python (for Ansible)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Create SSH Key from Secret
      run: |
        echo "${{ secrets.AWS_PEM_KEY }}" > aws-key.pem
        chmod 400 aws-key.pem

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini run-l1s.yml
